  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  sudo: required

  before_install:
    - pip install nose2 fcsparser tables matplotlib

  install:
    - cd python
    - python setup.py install
    - cd ..

  script:
    - cd python
    - python -m nose2 -v